---
title: Finally! How I got my blog to work...
author: Regina Manansala
date: '2020-08-21'
# image: ""
slug: hello
categories:
  - blog
keywords: 
  - blog
  - intro
description: A Covid-19 Summer Activity
excerpt: ""
---
Finally! This blog was over a year in the making, but I finally managed to get it to work.
It took me a **REALLY** long time to realize that my dissatisfaction with my GitHub username was causing all the blog deployment hiccups.

I've been intending to start a blog as a showcase or dumping site of sorts. It might be a slow start because I'm learning the intricacies of blogdown and GitHub, as well as deciding on how to appropriately structure my content without becoming a huge mess.

I guess I'll start by sharing the resources I found most useful in creating this blog.
<br> - https://www.andrea-rau.com/post/hello-blogdown/
<br> - https://www.tylerclavelle.com/code/2017/blogdown/
<br> - https://alison.rbind.io/post/2017-06-12-up-and-running-with-blogdown/
<br> - https://bookdown.org/yihui/blogdown/


The first link (an old colleague - Andrea) was a huge inspiration for me to create the blog and I'm not ashamed to say how much I frequented her GitHub repositories ("blogdown_source" and "andreamrau.github.io") during this blog creation process. The next two were the most helpful with actually getting started with blogdown and were suggested to me by Andrea. Finally, the last link was helpful due to how it's structured and might be a good resource should I choose to eventually switch to Netlify.

I might play around with the look and feel of the blog in the coming days (or weeks), so things might look a bit different around here. Until then, I'll continue to blog about what I am learning during this process and maybe other things that have been keeping me busy.