---
title: Reflections on CS 250
author: Regina Manansala
date: '2020-08-24'
slug: cs250
type: blog
categories:
  - blog
tags: 
  - blog
description: A Covid-19 Summer Activity (Part 2)
excerpt: ""
---

Over the summer, the members of my lab had the opportunity to audit UW-Milwaukee's Introduction to Programming class. It was 8 weeks long and entirely online. This was my first time ever taking a class online that wasn't one those free online short courses from Coursera or FutureLearn. In the weeks prior, I was witness to my sister's abrupt transition to online classes due to Covid-19 so I expected my course follow a similar format as hers - set lecture times where you watch a video or slideshow with a professor's voiceover, small group discussion sections, and online homework questionnaires/assignments.

I was wrong. The course was almost entirely self-taught. We were assigned chapters to read during the week with a set of accompanying homework questions, a coding assignment via repl.it, a short quiz, and responses to discussion questions. I enjoyed the repl.it assignments the most. It was a good way to practice code we learned that week while also building on code we'd learned the previous weeks. Also, repl.it is an amazing resource for learning a new programming language. The discussion questions, on the other hand, were not my cup of tea and I barely responded to them (I would've if I wasn't just an auditor). It probably would've felt less nitpicky to have to add additional comments or corrections to other people's responses had these discussions been in person.

Overall, I wish the course hadn't been so "detached". None of the code was demonstrated beyond what was written in the textbook and over time, the feedback on the assignments became less and less helpful. It wasn't clear what the professor nor the TA was looking for with regard to "style", but I'm not sure how much of that was due to my enrollment status. For what I was able to self-teach, I have a decent grasp on the basics of Java and I'm hoping that doesn't escape me during the short break we have before starting the next course in the series.
